name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  release:
    types: [published]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - macos-latest
        ocaml-version:
          - 5.3.x

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y bubblewrap g++-multilib gcc-multilib mercurial musl-tools rsync

      - name: Set up OCaml ${{ matrix.ocaml-version }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-version }}
          dune-cache: true
          opam-disable-sandboxing: true

      - name: Install dependencies
        run: |
          opam pin add mel-bastet.dev . --no-action
          opam install . --deps-only --with-test

      - name: Build
        run: opam exec -- dune build @install

      - name: Lint opam file
        run: opam lint mel-bastet.opam

      - name: Run tests
        run: opam exec -- dune runtest

  deploy:
    needs: test
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/main' || (github.event_name == 'release' && github.event.action == 'published')
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bubblewrap g++-multilib gcc-multilib mercurial musl-tools rsync

      - name: Set up OCaml 5.3.x
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 5.3.x
          dune-cache: true
          opam-disable-sandboxing: true

      - name: Install opam-publish
        run: opam install opam-publish

      - name: Configure git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Publish to opam (dry run)
        if: github.event_name != 'release'
        run: |
          echo "Dry run: opam publish --tag=main ."
          opam publish --dry-run .

      - name: Publish to opam (release)
        if: github.event_name == 'release' && github.event.action == 'published'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          opam publish --tag=${{ github.ref_name }} .
